- README.md
> setup dontation button

- Dockerfile.builder
- builder.bash
> fixing releasing

- .github/workflows/actions-deploy.yml
- README.md
- builder.bash
Check tag before try to run the complete CD
> First check tag

- README.alpha.md
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Containers.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAO.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAOMock.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAO.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworks.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DpsContainerManager.java
- src/main/java/com/mageddo/dnsproxyserver/docker/EventListener.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Labels.java
- src/main/java/com/mageddo/dnsproxyserver/docker/NetworkComparator.java
- src/main/java/com/mageddo/dnsproxyserver/docker/domain/Network.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfig.java
- src/main/resources/application.properties
> DPS 3 - Docker networks

- README.alpha.md
- src/main/java/com/mageddo/dnsproxyserver/App.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerHostnameMatcher.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Docker.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAO.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAOMock.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworks.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Labels.java
- src/main/java/com/mageddo/dnsproxyserver/docker/NetworkComparator.java
- src/main/java/com/mageddo/dnsproxyserver/docker/domain/Network.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfig.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/DockerSolver.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
- src/main/resources/META-INF/native-image/dps/native-image.properties
- src/main/resources/META-INF/native-image/dps/reflect-docker-java-command-core.json
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerHostnameMatcherTest.java
- src/test/java/com/mageddo/utils/templates/InspectContainerResponseTemplates.java
- src/test/resources/templates/nginx.json
> DPS 3 - Docker Register Service Names

- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/DockerSolver.java
> DPS - 3 Run despite docker

- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDocker.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemote.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/ServerStarterTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemoteTest.java
> DPS 3 - Refactoring solver names

- app/package.json
- app/public/index.html
- app/src/components/RecordForm.js
- docs/content/5-developing/_index.en.md
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAO.java
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/JsonConfigs.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/predicate/JsonEnvPredicate.java
- src/main/java/com/mageddo/dnsproxyserver/config/predicate/EntryPredicate.java
- src/main/java/com/mageddo/dnsproxyserver/config/predicate/EnvPredicate.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/IP.java
- src/main/java/com/mageddo/dnsproxyserver/server/rest/EnvResource.java
- src/main/java/com/mageddo/dnsproxyserver/server/rest/HostnameResource.java
- src/main/java/com/mageddo/dnsproxyserver/server/rest/reqres/EnvV1.java
- src/main/java/com/mageddo/dnsproxyserver/server/rest/reqres/HostnameV1.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
- src/main/java/com/mageddo/utils/Bytes.java
> DPS 3 - GUI REST API

- Dockerfile.java
- README.alpha.md
- docker-compose-tmp.yml
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/Quarkus.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Hostnames.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/ServerStarter.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDelegate.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverProvider.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/Solvers.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/ServerStarterTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystemTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EntryTemplates.java
- src/test/java/com/mageddo/utils/templates/SolverTemplates.java
> DPS - 3 LocalDB Solver CNAME Support

- README.alpha.md
- build.gradle
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/DpsIpDiscover.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DpsContainerManager.java
- src/main/java/com/mageddo/dnsproxyserver/net/Networks.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfig.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/IP.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/IpAddr.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/ServerStarter.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/SimpleServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/Solver.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDocker.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystem.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/Solvers.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolversCache.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
- src/main/java/com/mageddo/utils/Priorities.java
> DPS - 3 DNS Resolution Hangs Fixes

- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Docker.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerService.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDocker.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolversCache.java
> DPS 3 -  Minimal debug log

- RELEASE-NOTES.md
- build.gradle
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Hostname.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/TCPServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Wildcards.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/Solver.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDelegate.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDocker.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverMock.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystem.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolversCache.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDelegateTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolversCacheTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EntryTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/MessageTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/SolverMockTemplates.java
- src/test/java/com/mageddo/utils/Assertions.java
Partially fixing: https://github.com/mageddo/dns-proxy-server/issues/267
> DPS 3 - Query response not set fix

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/net/Networks.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/ServerStarter.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/SimpleServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServer.java
> DPS 3 - DPS Crashes when offline

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/net/Networks.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServerPool.java
- src/test/java/com/mageddo/dnsproxyserver/net/NetworksTest.java
* DPS 3 - Work only with up interfaces 
* Re-activate loopback interfaces
> DPS 3 - Work only with up interfaces

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/server/dns/DnsQueryTCPHandler.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/SocketClient.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/TCPServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServer.java
- src/main/resources/application.properties
- src/test/java/com/mageddo/dnsproxyserver/server/dns/DnsQueryTCPHandlerTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/SocketClientTemplates.java
> Better error treating and log formatting

- RELEASE-NOTES.md
- src/main/java/com/mageddo/commons/lang/Singletons.java
- src/main/java/com/mageddo/dnsproxyserver/App.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/DnsConfigurator.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/DnsConfigurators.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxDnsConfigurator.java
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigsTest.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxDnsConfiguratorTest.java
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerHostnameMatcherTest.java
> Respecting OS to configure as default DNS

- RELEASE-NOTES.md
- docs/content/1-getting-started/running-it/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/server/dns/DnsQueryTCPHandler.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/TCPServer.java
> Updating the windows running docs

- RELEASE-NOTES.md
- examples/wildcards/README.md
- examples/wildcards/docker-compose.yml
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerHostnameMatcher.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Docker.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAO.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkService.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerService.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DpsContainer.java
- src/test/java/com/mageddo/dnsproxyserver/docker/DockerServiceTest.java
- src/test/java/com/mageddo/dnsproxyserver/docker/DpsContainerTest.java
> Hostnames Env fixing

- RELEASE-NOTES.md
- docker-compose-dev.yml
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigEnv.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/DnsConfigurators.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxDnsConfigurator.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxResolverConfDetector.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvFile.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/resolvconf/DnsServerCleanerHandler.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/resolvconf/SetMachineDNSServerHandler.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DpsContainer.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Envs.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Splits.java
- src/main/java/com/mageddo/utils/Files.java
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigsTest.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxDnsConfiguratorTest.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxResolverConfDetectorTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/ConfigTemplates.java
- src/test/resources/configs-test/001.json
- src/test/resources/configs-test/004.json
Based on #321 , it fixes
> 2 => MG_RESOLVCONF will now accept more than one value
> 3 => The default value of MG_RESOLVCONF will changes to ...
> Multiple resolvconf paths support

- README.md
- RELEASE-NOTES.md
- docs/content/1-getting-started/_index.en.md
- docs/content/1-getting-started/running-it/_index.en.md
- docs/content/3-configuration/_index.en.md
- docs/content/_index.en.md
- docs/layouts/partials/toc.html
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/JsonConfigs.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/RequestHandlerDefault.java
- src/test/resources/configs-test/002.json
Documenting feature introduced at #321
> Docs updates for 3.4+ features

- README.md
- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAO.java
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Hostname.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Hostnames.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigDAOJsonTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EnvTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/IpTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/MessageTemplates.java
* LocalSolverDB Wildcards fix: wasn't working 
* LocalSolverDB Case sensitive query fixes: camelCase hostnames weren't being solved
> Fixes | LocalSolverDB Wildcards and Case sensitive  query fixes

- README.md
- RELEASE-NOTES.md
- docs/content/5-developing/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/DnsConfigurator.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/DnsConfigurators.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxDnsConfigurator.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvconfConfigurator.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvedConfigurator.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/IpAddr.java
- src/main/java/com/mageddo/dnsproxyserver/utils/DNS.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/DnsConfiguratorsTest.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/LinuxDnsConfiguratorTest.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvconfConfiguratorTest.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/systemdresolved/ResolvedConfiguratorTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/IpAddrTemplates.java
> Configure system-resolved with a custom port when needled

- README.md
- RELEASE-NOTES.md
- docs/content/3-configuration/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/utils/Envs.java
- src/test/java/com/mageddo/dnsproxyserver/utils/EnvsTest.java
> Better resilience for env flags parse

- Dockerfile.builder.linux-aarch64
- Dockerfile.builder.linux-amd64
- README.md
- build.gradle
- builder.bash
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/package-info.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/TCPServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/rest/reqres/ReflectConfig.java
- src/main/java/com/mageddo/dnsproxyserver/server/rest/reqres/package-info.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
- src/main/java/com/mageddo/jna/package-info.java
- src/main/resources/META-INF/native-image/dps/native-image.properties
> Dagger 2: Fixing arm64 build

- Dockerfile.builder.linux-aarch64
- src/main/java/com/mageddo/dnsproxyserver/App.java
- src/main/java/com/mageddo/dnsproxyserver/AppSettings.java
- src/main/java/com/mageddo/dnsproxyserver/LogLevelSetup.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/LogLevel.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfig.java
- src/main/java/com/mageddo/logback/LogbackUtils.java
- src/main/resources/META-INF/native-image/dps/native-image.properties
- src/main/resources/META-INF/native-image/graal-generated/reflect-logback.json
- src/main/resources/logback-file.xml
- src/test/java/com/mageddo/dnsproxyserver/AppSettingsTest.java
Fixing log level configuring after quarkus removal
> Log level fix

- .github/ISSUE_TEMPLATE/bug-unexpected-behavior-report.md
- builder.bash
* Fixing latest image wasn't being pushed
* Updated the bug report template updating how to retrieve DPS version
> Minor fixes

- .github/workflows/actions-deploy.yml
- Dockerfile.builder.linux-aarch64
- README.md
- RELEASE-NOTES.md
- build.gradle
- builder.bash
- docker-compose-deploy.yml
- gradle.properties
> Incremental Releasing

- RELEASE-NOTES.md
- docs/content/1-getting-started/running-it/mac/_index.en.md
- docs/content/1-getting-started/running-it/windows/_index.en.md
- docs/content/5-tutorials/_index.en.md
- docs/content/5-tutorials/docker-reverse-proxy.en.md
- docs/content/api/_index.en.md
- docs/content/versions/_index.en.md
- examples/api-gateway_service-discovery_reverse-proxy/Dockerfile
- examples/api-gateway_service-discovery_reverse-proxy/docker-compose.yml
- examples/api-gateway_service-discovery_reverse-proxy/index.html
- examples/api-gateway_service-discovery_reverse-proxy/nginx/README.md
- examples/api-gateway_service-discovery_reverse-proxy/nginx/entrypoint.sh
- examples/api-gateway_service-discovery_reverse-proxy/nginx/nginx.conf
- examples/api-gateway_service-discovery_reverse-proxy/nginx/reverse-proxy.conf
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/DnsConfiguratorOSX.java
- src/main/java/com/mageddo/net/osx/NetworkOSX.java
- src/main/java/com/mageddo/net/osx/Networks.java
> Fixes and Docs Updates

- RELEASE-NOTES.md
- docs/content/2-features/solving-hostnames-wildcard/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAO.java
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerHostnameMatcher.java
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingService.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Docker.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Hostname.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Hostnames.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/HostnameMatcher.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/HostnameQuery.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDocker.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigDAOJsonTest.java
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerHostnameMatcherTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/CacheResourceCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/HostnameQueryTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDockerTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/HostnameQueryTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/HostnameTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/MessageTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/docker/InspectContainerResponseTemplates.java
- src/test/java/testing/ContextSupplier.java
- src/test/java/testing/Events.java
> Support for regex on hostname

- .gitattributes
- RELEASE-NOTES.md
- docs/content/1-getting-started/running-it/mac/_index.en.md
- docs/content/1-getting-started/running-it/windows/_index.en.md
- docs/content/5-tutorials/docker-reverse-proxy.en.md
- examples/api-gateway_service-discovery_reverse-proxy/Dockerfile
- examples/api-gateway_service-discovery_reverse-proxy/nginx/entrypoint.sh
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerConnectionCheck.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/IP.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystem.java
- src/main/java/com/mageddo/dnsproxyserver/usecase/HostMachineService.java
- src/test/java/com/mageddo/dnsproxyserver/config/flags/ConfigFlagTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystemCompTest.java
> Windows Binary: Docker containers Solving

- RELEASE-NOTES.md
- docs/content/1-getting-started/requirements/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/quarkus/DockerConfig.java
> Specify the docker api version

- docs/content/1-getting-started/running-it/linux/_index.en.md
Sometimes Linux distribution can have another program listening at 5353 like avahi, so I'm changing the published port
> Adjusting the docs

- RELEASE-NOTES.md
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingService.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAO.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerDAOMock.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkService.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/HostnameQuery.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystem.java
- src/main/java/com/mageddo/dnsproxyserver/usecase/HostMachineService.java
- src/main/java/com/mageddo/net/IP.java
- src/main/java/com/mageddo/net/IpImpl.java
- src/main/java/com/mageddo/net/Networks.java
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingServiceCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/docker/DockerDAODefaultTest.java
- src/test/java/com/mageddo/dnsproxyserver/docker/DockerNetworkServiceTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystemCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/InetAddressTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/IpTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/NetworkInterfaceTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/usecase/HostMachineServiceTest.java
- src/test/java/com/mageddo/net/NetworksTest.java
> SolverSystem: Support for Type AAAA Entries (IPv6)

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingService.java
- src/main/java/com/mageddo/dnsproxyserver/docker/Entry.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/HostnameQuery.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDocker.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystem.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigDAOJsonTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverDockerTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverSystemCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EntryTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EnvTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/HostnameQueryTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/HostnameTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/IpTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/docker/EntryTemplates.java
> LocalDB: Support for Type AAAA Entries (IPv6) 

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/docker/DpsContainerManager.java
> DPS Network IPV6 Support

- README.md
- RELEASE-NOTES.md
- app/src/components/RecordForm.js
- app/src/components/RecordTable.js
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV1EnvsConverter.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2EnvsConverter.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/main/java/com/mageddo/dnsproxyserver/server/rest/reqres/HostnameV1.java
- src/test/java/com/mageddo/dnsproxyserver/server/rest/HostnameResourceCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EntryTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EnvTemplates.java
- src/test/java/com/mageddo/net/IPTest.java
> Ajusting GUI for AAAA Support

- .gitignore
- RELEASE-NOTES.md
- docs/content/3-configuration/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigEnv.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigFlag.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV1.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ConfigureDPSHandler.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/DnsConfiguratorLinux.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvconfConfigurator.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvconfConfigureDPSHandler.java
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvedConfigureDPSHandler.java
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigsTest.java
- src/test/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/ResolvconfConfiguratorTest.java
- src/test/resources/config-json-v1-test/002.json
- src/test/resources/configs-test/001.json
- src/test/resources/configs-test/002.json
- src/test/resources/configs-test/004.json
- src/test/resources/flags-test/001.json
- src/test/resources/flags-test/002.txt
- src/test/resources/json-configs-test/001.json
> Option to not comment out existing nameservers from resolv.conf

- RELEASE-NOTES.md
- docs/content/1-getting-started/versioning.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAO.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/docker/DockerNetworkService.java
- src/main/java/com/mageddo/dnsproxyserver/docker/EventListener.java
- src/main/java/com/mageddo/dnsproxyserver/docker/domain/NetworkConnectionStatus.java
- src/test/java/com/mageddo/dnsproxyserver/docker/DockerNetworkDAODefaultTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/docker/DockerClientTemplates.java
- src/test/java/testing/mocks/DockerClientStub.java
> Fix: DPS Network autoconnect stops working 

- docker-compose-dev.yml
- docs/content/3-configuration/_index.en.md
> updating the docs

- RELEASE-NOTES.md
- docs/content/3-configuration/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigEnv.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigFlag.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV1.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/RequestHandlerDefault.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Envs.java
- src/test/java/com/mageddo/dnsproxyserver/config/entrypoint/JsonConfigsTest.java
- src/test/resources/config-json-v1-test/002.json
- src/test/resources/configs-test/001.json
- src/test/resources/configs-test/002.json
- src/test/resources/configs-test/004.json
- src/test/resources/flags-test/001.json
- src/test/resources/flags-test/002.txt
- src/test/resources/json-configs-test/001.json
> Introducing option to customize rcode

- RELEASE-NOTES.md
- build.gradle
- gradle.properties
- src/main/java/com/mageddo/commons/circuitbreaker/CircuitCheckException.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfig.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/RemoteResolvers.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/Resolver.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SimpleResolver.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemote.java
- src/main/java/com/mageddo/net/Networks.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemoteTest.java
- src/test/java/testing/templates/InetSocketAddressTemplates.java
> Circuit Breaker for Remote DNS Servers

- docker-compose-dev.yml
- docs/content/4-developing/_index.en.md
- gradle.properties
- src/main/resources/META-INF/native-image/dps/native-image.properties
- src/main/resources/META-INF/native-image/dps/reflect-docker-java-core.json
* Fixing Native Image Reflection JSON Parsing introduced at #432 
* Updating the developing docs
> Fixing Native Image Reflection JSON Parsing

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingService.java
- src/main/java/com/mageddo/dnsproxyserver/docker/MatchingContainerService.java
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingServiceCompTest.java
> DockerSolver: Leading with no IPV6 to answer 

- RELEASE-NOTES.md
- docs/content/3-configuration/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigEnv.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigFlag.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV1.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2.java
- src/main/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingService.java
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerSolvingServiceTest.java
- src/test/resources/config-json-v1-test/002.json
- src/test/resources/configs-test/001.json
- src/test/resources/configs-test/002.json
- src/test/resources/configs-test/004.json
- src/test/resources/flags-test/001.json
- src/test/resources/flags-test/002.txt
- src/test/resources/json-configs-test/001.json
> Feature toggle to turn off Host Machine IP fallback

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/package-info.java
> Fixing native image JSON config parse, bug introduced on 3.17.3

- RELEASE-NOTES.md
- docs/content/3-configuration/_index.en.md
- docs/content/4-developing/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigJsonV2.java
- src/main/resources/META-INF/native-image/dps/native-image.properties
- src/main/resources/META-INF/native-image/dps/reflect-jackson.json
> JSON Parsing Fix

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dns/utils/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
- src/main/java/com/mageddo/dnsserver/TCPServer.java
- src/main/java/com/mageddo/net/IpAddrs.java
- src/main/java/com/mageddo/net/NetExecutorWatchdog.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolverRemoteTest.java
Related to #455 
Refactor  `SolverRemote` class which is with really big methods, practice some clean code there.
> #455 - Refactoring SolverRemote

- RELEASE-NOTES.md
- src/main/java/com/mageddo/dnsproxyserver/di/Context.java
- src/main/java/com/mageddo/dnsproxyserver/di/StartupEvent.java
- src/main/java/com/mageddo/dnsproxyserver/di/module/ModuleMap.java
- src/main/java/com/mageddo/dnsproxyserver/di/module/ModuleStartup.java
- src/main/java/com/mageddo/dnsproxyserver/server/Starter.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/CircuitBreakerService.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerCheckerService.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerFactory.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerFailSafeService.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerNonResilientService.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/configurator/CircuitBreakerWatchDogScheduler.java
- src/main/java/com/mageddo/net/NetExecutorWatchdog.java
- src/main/java/com/mageddo/net/Networks.java
- src/test/java/com/mageddo/dnsproxyserver/solver/docker/entrypoint/EventListenerCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerCheckerServiceTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerFactoryTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerFailSafeServiceCompTest.java
- src/test/java/dagger/sheath/CtxWrapper.java
- src/test/java/dagger/sheath/ProviderWrapper.java
- src/test/java/testing/Events.java
- src/test/java/testing/templates/CircuitBreakerConfigTemplates.java
- src/test/java/testing/templates/solver/remote/FailSafeCircuitBreakerTemplates.java
> PR: Remote Server Solver Cache Consistency Guarantee

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsserver/TCPServer.java
- src/main/java/com/mageddo/net/NetExecutorWatchdog.java
- src/test/java/com/mageddo/net/NetExecutorWatchdogTest.java
- src/test/java/testing/templates/IpAddrTemplates.java
Resources usage optimization identified at #455
> Resources usage optimization

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/CircuitBreaker.java
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOCmdArgs.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOEnv.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/mapper/ConfigMapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/validator/CircuitBreakerValidator.java
- src/main/java/com/mageddo/dnsproxyserver/config/validator/ConfigValidator.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverProvider.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Booleans.java
- src/main/java/com/mageddo/dnsproxyserver/utils/ObjectUtils.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolverProviderTest.java
- src/test/java/testing/templates/ConfigTemplates.java
- src/test/resources/configs-test/001.json
- src/test/resources/configs-test/004.json
> Config module domain refactoring

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/net/IpAddr.java
- src/main/java/com/mageddo/net/IpImpl.java
- src/main/java/com/mageddo/net/IpUtils.java
- src/main/java/com/mageddo/net/Networks.java
Fixing usecase invalid ip was being tried to be solved as hostname from internet
> Fixing invalid IP parsing usecase

- .github/workflows/actions-deploy.yml
- .github/workflows/ci.yml
- Dockerfile.builder.linux-aarch64
- Dockerfile.builder.linux-amd64
- RELEASE-NOTES.md
- gradle.properties
> #435 GraalVM Upgrade to 21 LTS

- Dockerfile.builder.linux-aarch64
> Fixing arch image 

- Dockerfile.builder.linux-aarch64
- Dockerfile.builder.linux-amd64
> fixing linux image ref

- .github/workflows/actions-deploy.yml
- Dockerfile.amd64-static
- Dockerfile.builder.linux-aarch64
- Dockerfile.builder.linux-amd64
- Dockerfile.builder.linux-amd64-static
- RELEASE-NOTES.md
- gradle.properties
- src/main/docker/builder/sources.list
- src/main/java/com/mageddo/dnsproxyserver/App.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigFlag.java
- src/main/java/com/mageddo/net/SocketUtils.java
- src/test/java/com/mageddo/dnsproxyserver/AppCompTest.java
- src/test/java/com/mageddo/net/SocketUtilsTest.java
- src/test/java/testing/ContextSupplier.java
- src/test/resources/flags-test/001.json
> Fixing amd64 static docker image and min glibc to 2.15

- docs/content/1-getting-started/requirements/_index.en.md
- docs/content/1-getting-started/running-it/_index.en.md
> Updating the min reqs to build and run due java upgrade to 21

- .github/workflows/actions-deploy.yml
- Dockerfile.builder.linux-amd64
- RELEASE-NOTES.md
- build.gradle
- gradle.properties
> Java 21 upgrade fixes

- Dockerfile.builder.linux-aarch64
- RELEASE-NOTES.md
- gradle.properties
- src/main/docker/builder-aarch64/sources.list
> Downgrade necessary libc version to run aarch binary

- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/JsonConfigs.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2Mapper.java
- src/test/java/com/mageddo/dnsproxyserver/config/application/ConfigServiceCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOJsonTest.java
- src/test/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2MapperTest.java
- src/test/java/testing/templates/ConfigJsonTemplates.java
- src/test/resources/configs-test/005.json
- src/test/resources/configs-test/006.json
- src/test/resources/configs-test/007.json
Refactoring and tests created due #513 , before fixing the code
> #513 Refactoring  on ConfigJson Module

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2Mapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigJsonV1.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigJsonV2.java
- src/test/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2MapperTest.java
- src/test/java/testing/templates/ConfigJsonTemplates.java
- src/test/resources/configs-test/008.json
> Fixing `noRemoteServers` wasn't being respected at the JSON file #513

- RELEASE-NOTES.md
- gradle.properties
- src/main/docker/qemu/Dockerfile
> Mitigate arm release failure due inexistence of required debian package #517

- src/main/java/com/mageddo/dnsproxyserver/solver/RemoteResolvers.java
- src/main/java/com/mageddo/dnsserver/TCPServer.java
- src/main/java/com/mageddo/dnsserver/UDPServer.java
- src/main/java/com/mageddo/net/NetExecutorWatchdog.java
- src/main/java/com/mageddo/utils/Executors.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolverRemoteTest.java
- src/test/java/com/mageddo/utils/ExecutorsTest.java
> Internal feature toggle to disable virtual threads

- RELEASE-NOTES.md
- build.gradle
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverCache.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolversCacheTest.java
> Migrating cache to caffeine

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverRemote.java
- src/main/java/com/mageddo/net/IpAddr.java
- src/main/java/com/mageddo/net/IpAddrs.java
- src/main/java/com/mageddo/net/Networks.java
- src/main/java/com/mageddo/net/SocketUtils.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolverRemoteTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerCheckerServiceTest.java
- src/test/java/com/mageddo/net/NetworksTest.java
> Disable connection check at every query

- .gitignore
- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverCacheFactory.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerCheckerService.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerFactory.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerFailSafeService.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/configurator/CircuitBreakerWatchDogScheduler.java
- src/test/java/com/mageddo/dnsproxyserver/solver/remote/application/CircuitBreakerFactoryTest.java
- src/test/java/testing/templates/CircuitBreakerConfigTemplates.java
- src/test/java/testing/templates/solver/remote/ResultSupplierTemplates.java
> More Effective RemoteSolver Circuit Check #526

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/solver/RemoteResolvers.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/Request.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/ResolverStats.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/ResolverStatsFactory.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/mapper/ResolverMapper.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolverRemoteTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/remote/application/ResolverStatsFactoryTest.java
- src/test/java/testing/templates/InetSocketAddressTemplates.java
- src/test/java/testing/templates/solver/remote/ResolverTemplates.java
> SolverRemote: Exclude remote servers with open circuits. #526

- .github/workflows/actions-deploy.yml
> CD Deps Fix

- src/main/java/com/mageddo/dnsproxyserver/server/Starter.java
- src/test/java/com/mageddo/dnsproxyserver/server/StarterTest.java
> Creating flag to force dns server start even when in test mode #480

- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigPathBuilder.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/JsonConfigs.java
- src/test/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOJsonTest.java
> Create default JSON config file with default values 

- RELEASE-NOTES.md
- build.gradle
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/CircuitBreakerStrategy.java
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/config/StaticThresholdCircuitBreakerStrategy.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2Mapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/mapper/ConfigMapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/validator/CircuitBreakerValidator.java
- src/main/java/com/mageddo/dnsproxyserver/config/validator/ConfigValidator.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/failsafe/CircuitBreakerFactory.java
- src/test/java/testing/templates/CircuitBreakerConfigTemplates.java
> Agnostic interface to support multiple circuit breaker strategies config

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/failsafe/CircuitBreakerFactory.java
- src/test/java/com/mageddo/dnsproxyserver/solver/remote/application/failsafe/CircuitBreakerFactoryTest.java
> Fixing SolverRemote NPE #533

- RELEASE-NOTES.md
- docs/content/3-configuration/_index.en.md
- gradle.properties
- src/main/docker/qemu/Dockerfile
- src/main/java/com/mageddo/dnsproxyserver/config/application/ConfigFileFinderService.java
- src/main/java/com/mageddo/dnsproxyserver/config/application/ConfigPathMapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigPathBuilder.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigFlagMapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigEnv.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigFlag.java
- src/test/java/com/mageddo/dnsproxyserver/config/application/ConfigFileFinderServiceTest.java
- src/test/java/com/mageddo/dnsproxyserver/config/application/ConfigPathMapperTest.java
- src/test/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOJsonTest.java
- src/test/java/testing/templates/ConfigFlagArgsTemplates.java
- src/test/java/testing/templates/ConfigFlagTemplates.java
- src/test/java/testing/templates/config/ConfigEnvTemplates.java
- src/test/resources/flags-test/001.json
- src/test/resources/flags-test/002.txt
It is needle to create new native int tests to test bugs produced in issue #533
> Specify config file path by env and fixing arm release

- src/main/java/com/mageddo/wait/ExpectedConditions.java
- src/main/java/com/mageddo/wait/UnsatisfiedConditionException.java
- src/main/java/com/mageddo/wait/Wait.java
- src/test/java/com/mageddo/wait/WaitTest.java
Relates to #533 
Module will be used on the IntTests which will be created to continually check conditions until they happen or timeouts.
> Wait module

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/commons/exec/CommandLines.java
- src/main/java/com/mageddo/commons/exec/DelegateOutputStream.java
- src/main/java/com/mageddo/commons/exec/ExecutionValidationFailedException.java
- src/main/java/com/mageddo/commons/exec/NopResultHandler.java
- src/main/java/com/mageddo/commons/exec/PipedStream.java
- src/main/java/com/mageddo/commons/exec/ProcessAccessibleDaemonExecutor.java
- src/main/java/com/mageddo/commons/exec/ProcessesWatchDog.java
- src/main/java/com/mageddo/commons/exec/Request.java
- src/main/java/com/mageddo/commons/exec/Result.java
- src/main/java/com/mageddo/concurrent/ThreadsV2.java
- src/main/java/com/mageddo/io/LogPrinter.java
- src/test/java/com/mageddo/commons/exec/CommandLinesTest.java
- src/test/java/com/mageddo/commons/exec/DelegateOutputStreamTest.java
- src/test/java/com/mageddo/commons/exec/PipedStreamTest.java
Relates to #533
Commandline module upgrade to be able to execute usecases when creating new  native int tests
> CommandLine module upgrades

- RELEASE-NOTES.md
- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/application/ConfigService.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/ConfigDAOEnv.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigFlagMapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2Mapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigEnv.java
- src/main/java/com/mageddo/dnsproxyserver/config/mapper/ConfigMapper.java
- src/test/java/com/mageddo/dnsproxyserver/AppSettingsTest.java
- src/test/java/testing/templates/ConfigTemplates.java
- src/test/resources/configs-test/001.json
- src/test/resources/configs-test/004.json
Specify from which source the config is coming to facilitate troubleshooting.
Relates to #533
> Specifying config source

- .github/workflows/ci.yml
- RELEASE-NOTES.md
- build.gradle
- gradle.properties
- src/main/java/com/mageddo/dns/utils/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/sandbox/BinaryFromGradleTestsSandbox.java
- src/main/java/com/mageddo/dnsproxyserver/sandbox/DpsBinaryExecutableFinder.java
- src/main/java/com/mageddo/dnsproxyserver/sandbox/Instance.java
- src/main/java/com/mageddo/dnsproxyserver/sandbox/Sandbox.java
- src/test/java/com/mageddo/dnsproxyserver/AppIntTest.java
- src/test/java/com/mageddo/dnsproxyserver/sandbox/DpsBinaryExecutableFinderIntTest.java
- src/test/java/com/mageddo/dnsproxyserver/sandbox/SandboxTest.java
- src/test/java/testing/templates/ConfigFlagArgsTemplates.java
- src/test/java/testing/templates/ConfigJsonFileTemplates.java
Implementing an IntTest which can validate the happy path of all DPS solvers, 
being able to detect bugs like the fixed at 3.25.14 (6db82f50d54bd3f3aed15d7120c1963c0386abf4).
Relates to #533
> Int test for all solvers

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/di/Eager.java
- src/main/java/com/mageddo/dnsproxyserver/di/Context.java
- src/main/java/com/mageddo/dnsproxyserver/di/module/ModuleEager.java
- src/main/java/com/mageddo/dnsproxyserver/di/module/ModuleStartup.java
- src/main/java/com/mageddo/json/JsonUtils.java
- src/test/java/com/mageddo/dnsproxyserver/di/ContextCompTest.java
Module to beans which need to initialize on app startup, different of StartupEvent, Eager are not coupled to DPS logic.
Relates to #533
> Eager module

- .github/workflows/release-latest.yml
> Static tag for amd64 latest image

- docs/content/2-features/auto-configuration-as-default-dns/_index.en.md
Fixing broken links at the docs  - Relates to #580
> Fixing broken links at the docs

- RELEASE-NOTES.md
- docker-compose-dev.yml
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/dnsconfigurator/linux/DnsConfiguratorLinux.java
- src/main/java/com/mageddo/io/path/predicate/PathExistsPredicate.java
- src/main/java/com/mageddo/io/path/predicate/PathIsFilePredicate.java
- src/main/java/com/mageddo/io/path/predicate/PathIsWritablePredicate.java
Refactoring file edition conditions to rule pattern this way I can detect which condition didn't match and log the cause
Relates to #580
> Detect which condition didn't match and log the cause when configuring DPS as default DNS

- RELEASE-NOTES.md
- gradle.properties
- src/main/resources/META-INF/native-image/dps/native-image.properties
> Adjusting binary generation to compatibility

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/mapper/NetworkMapper.java
- src/test/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/mapper/NetworkMapperTest.java
- src/test/java/testing/templates/docker/NetworkTemplates.java
- src/test/resources/templates/docker/network/005.json
> Bugfix: Treating npe at networks mapping when network hasn't a gateway ip #580

- RELEASE-NOTES.md
- docs/content/2-features/remote-solver-circuitbreaker/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2Mapper.java
- src/main/java/com/mageddo/dnsproxyserver/config/dataprovider/vo/ConfigJsonV2.java
- src/main/java/com/mageddo/dnsproxyserver/config/validator/CircuitBreakerValidator.java
- src/main/java/com/mageddo/dnsproxyserver/config/validator/ConfigValidator.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/application/failsafe/CircuitBreakerFactory.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Numbers.java
- src/test/java/com/mageddo/dnsproxyserver/config/application/ConfigServiceCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/config/dataprovider/mapper/ConfigJsonV2MapperTest.java
- src/test/java/com/mageddo/dnsproxyserver/config/entrypoint/JsonConfigsTest.java
- src/test/java/testing/templates/ConfigJsonTemplates.java
- src/test/resources/configs-test/009.json
> Exposing Canary Rate Threshold to be configurable and usable

- RELEASE-NOTES.md
- docs/content/2-features/stub-solver/_index.en.md
- docs/content/3-configuration/_index.en.md
- gradle.properties
- src/main/java/com/mageddo/dns/Hostname.java
- src/main/java/com/mageddo/dns/utils/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/di/module/ModuleSolver.java
- src/main/java/com/mageddo/dnsproxyserver/solver/Response.java
- src/main/java/com/mageddo/dnsproxyserver/solver/ResponseMapper.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverProvider.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverSystem.java
- src/main/java/com/mageddo/dnsproxyserver/solver/stub/HostnameIpExtractor.java
- src/main/java/com/mageddo/dnsproxyserver/solver/stub/SolverStub.java
- src/main/java/com/mageddo/net/IP.java
- src/test/java/com/mageddo/dns/HostnameTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/stub/SolverStubTest.java
- src/test/java/testing/templates/MessageTemplates.java
> Configuring Stub Solver

- build.gradle
- src/main/java/com/mageddo/dnsproxyserver/docker/dataprovider/ContainerFacade.java
- src/main/java/com/mageddo/dnsproxyserver/docker/dataprovider/ContainerFacadeDefault.java
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/ContainerDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/DpsContainerDAODefault.java
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerFacadeDefaultTest.java
- src/test/java/com/mageddo/dnsproxyserver/docker/dataprovider/ContainerFacadeDefaultCompTest.java
- src/test/java/com/mageddo/dnsproxyserver/docker/dataprovider/ContainerFacadeDefaultTest.java
Refactoring changes made at #599
> Refactoring
