mageddo/dns-proxy-server

- src/github.com/mageddo/dns-proxy-server/flags/flags.go
- src/github.com/mageddo/dns-proxy-server/service/docker.go
- src/github.com/mageddo/dns-proxy-server/service/service.go
From version *2.0.4* when running Dns Proxy Server in service docker mode mode the web port is published, it can be a not desired behavior, so should be  optional
> MG-362 option to enable/disable web server publish port

- events/docker/docker.go
- events/docker/docker_test.go
Currently to resolve docker service names, DPS always add ".docker" suffix to the docker service name, I guess because this is the default DPS domain.
This PR modifies this behavior to use the configured DPS domain instead of the default "docker" domain.
Tests have been modified to reflect the docker-compose behavior of adding "_1" to the container name created for a docker service.
> Resolving docker services using configured DPS domain.

- conf/conf.go
The existing check accidentally checked the length of the HostMachineHostname
instead of the Domain configuration setting to determine if the Domain setting
was present.
> Fix presence check of config setting "domain"

- src/main/java/com/mageddo/dnsproxyserver/config/Config.java
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAO.java
- src/main/java/com/mageddo/dnsproxyserver/config/ConfigDAOJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/config/EntryType.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJson.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV1.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV1EnvsConverter.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV2EnvsConverter.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/JsonConfigs.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/IP.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/IpAddr.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/Messages.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDB.java
- src/main/resources/META-INF/native-image/dps/native-image.properties
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigsTest.java
- src/test/java/com/mageddo/dnsproxyserver/config/entrypoint/ConfigJsonV1Test.java
- src/test/java/com/mageddo/dnsproxyserver/config/entrypoint/JsonConfigsTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/ServerStarterTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverLocalDBTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/ConfigTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EntryTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/EnvTemplates.java
- src/test/resources/config-json-v1-test/002.json
- src/test/resources/configs-test/001.json
- src/test/resources/configs-test/002.json
- src/test/resources/configs-test/004.json
- src/test/resources/json-configs-test/001.json
> DPS 3 - Local DB Solver

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/config/Configs.java
- src/main/java/com/mageddo/dnsproxyserver/config/entrypoint/LogLevel.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfig.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolverRemote.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/solver/SolversCache.java
- src/main/java/com/mageddo/utils/Files.java
- src/main/java/com/mageddo/utils/Runtime.java
- src/main/resources/application.properties
- src/test/java/com/mageddo/dnsproxyserver/config/ConfigsTest.java
- src/test/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfigTest.java
- src/test/java/com/mageddo/dnsproxyserver/server/dns/solver/SolversCacheTest.java
- src/test/java/com/mageddo/dnsproxyserver/templates/ConfigFlagTemplates.java
- src/test/java/com/mageddo/dnsproxyserver/templates/ConfigTemplates.java
Partially fixes https://github.com/mageddo/dns-proxy-server/issues/267
> DPS 3 -  Minor fixes

- app/package-lock.json
- app/package.json
Removes [ansi-html](https://github.com/Tjatse/ansi-html). It's no longer used after updating ancestor dependency [react-scripts](https://github.com/facebook/create-react-app/tree/HEAD/packages/react-scripts). These dependencies need to be updated together.
Removes `ansi-html`
Updates `react-scripts` from 3.0.1 to 5.0.1
- [Release notes](https://github.com/facebook/create-react-app/releases)
- [Changelog](https://github.com/facebook/create-react-app/blob/main/CHANGELOG-3.x.md)
- [Commits](https://github.com/facebook/create-react-app/commits/react-scripts@5.0.1/packages/react-scripts)
---
updated-dependencies:
- dependency-name: ansi-html dependency-type: indirect
- dependency-name: react-scripts dependency-type: direct:production ...
> Bump ansi-html and react-scripts in /app (#263)

- src/main/java/com/mageddo/dnsproxyserver/net/Networks.java
- src/main/java/com/mageddo/dnsproxyserver/quarkus/QuarkusConfig.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/ServerStarter.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/SimpleServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServer.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServerPool.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
I was using WILDCARD to create the DatagramSocket `new DatagramSocket(port)` but was getting issues, by some reason the dns clients like nslookup wasn't able the get the responses when querying using a virtual network interface like docker, when querying using the real interfaces or 127.0.0.1 it worked.
Solution was to start one UDP server for every interface this way all worked
> DPS 3 - Bind UDP server to all available interfaces

- .github/workflows/actions-deploy.yml
- RELEASE-NOTES.md
- build.gradle
- docker-compose-dev.yml
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/di/StartupEvent.java
- src/main/java/com/mageddo/dnsproxyserver/di/module/ModuleStartup.java
- src/main/java/com/mageddo/dnsproxyserver/server/dns/UDPServerPool.java
- src/main/java/com/mageddo/dnsproxyserver/utils/Ips.java
- src/test/java/com/mageddo/dnsproxyserver/docker/EventListenerCompTest.java
* Binding UDP server to anylocalhost just as TCP this way DPS can be used on any interface.
* Disabling mac as the binary isn't working macos-latest, see #341
* Fixing DPS network features startup
> Minor Fixes

- RELEASE-NOTES.md
- build.gradle
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/quarkus/DockerConfig.java
Fixes #431 
[Tests are passing](https://github.com/ThisIsQasim/dns-proxy-server/actions/runs/7669451043)
> Bump Docker client API to fix compatibility with Docker version 25

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/docker/domain/Drivers.java
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/Network.java
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/DockerDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/mapper/NetworkMapper.java
- src/test/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/DockerDAODefaultTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/mapper/NetworkMapperTest.java
- src/test/java/testing/templates/docker/NetworkTemplates.java
- src/test/java/testing/templates/server/dns/solver/docker/NetworkTemplates.java
- src/test/resources/templates/docker/network/003.json
Fixing error when fallback to host machine IP, Network mapper fails when the mapped networks hasn't  an IPAM config, it has more chances to happen on IPV6 query solving.
Relates to #474 .
> #474 Fixing error when fallback to host machine IP 

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/mapper/NetworkMapper.java
- src/test/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/mapper/NetworkMapperTest.java
- src/test/java/testing/templates/docker/NetworkTemplates.java
- src/test/resources/templates/docker/network/004.json
As reported at #427, For a unidentified reason, sometimes network api  responds an IPV6 with a subnet mask instead of a plain IP which is the expected behavior, a hotfix for that was made to extract the IP from this string when it happens, it only happens with ipv6 addresses.
Expected address
```
"Gateway": "fddb:21e4:36d4:2::1"
```
Actual address
```
"Gateway": "fddb:21e4:36d4:2::1/64"
```
> #427: Hotfix for ipv6 represented as subnet usecase

- .github/workflows/actions-deploy.yml
- Dockerfile.builder.linux-aarch64
- RELEASE-NOTES.md
- docker-compose-qemu.yaml
- gradle.properties
- src/main/docker/qemu/Dockerfile
> #473 Qemu upgrading 

- RELEASE-NOTES.md
- build.gradle
- gradle.properties
Fixed Jar release which was broken when upgraded to java 21.
> #435: Fixed Jar release which was broken when upgraded to java 21 at `3.22.0`

- Dockerfile.builder.linux-aarch64
- RELEASE-NOTES.md
- gradle.properties
> Build Aarch64 image with page size of 64k to Increase Compatibility

- RELEASE-NOTES.md
- build.gradle
- gradle.properties
> Ensure thread will have names at the logs, behavior changed since `3.25.0` 

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/concurrent/SingleThreadQueueProcessor.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverCache.java
- src/main/java/com/mageddo/dnsproxyserver/solver/SolverCacheFactory.java
- src/main/java/com/mageddo/dnsproxyserver/solver/remote/dataprovider/SolverConsistencyGuaranteeDAOImpl.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolverCacheFactoryTest.java
- src/test/java/com/mageddo/dnsproxyserver/solver/SolversCacheTest.java
- src/test/java/testing/templates/MessageTemplates.java
- src/test/resources/logback-test.xml
> Change the caching strategy to minimize the locks and prevent deadlocks #522

- .github/workflows/actions-deploy.yml
- .github/workflows/ci.yml
- .github/workflows/close-inative-waiting-feedback-issues.yml
- .github/workflows/docs.yml
- .github/workflows/release-latest.yml
Fixing docker-compose deps was missing
> CD Deps Fix

- src/main/java/com/mageddo/utils/Tests.java
- src/test/java/com/mageddo/utils/TestsTest.java
* Caching in test method
* Leading with usecase when a second thread is running the test
Relates to #480
> Tests utils class improvements

- RELEASE-NOTES.md
- gradle.properties
- src/main/java/com/mageddo/dnsproxyserver/App.java
- src/test/java/com/mageddo/dnsproxyserver/AppCompTest.java
> Handling and logging fatal errors

- build.gradle
- src/main/java/com/mageddo/dnsproxyserver/docker/dataprovider/ContainerFacade.java
- src/main/java/com/mageddo/dnsproxyserver/docker/dataprovider/ContainerFacadeDefault.java
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/ContainerDAODefault.java
- src/main/java/com/mageddo/dnsproxyserver/solver/docker/dataprovider/DpsContainerDAODefault.java
- src/test/java/com/mageddo/dnsproxyserver/docker/ContainerFacadeDefaultTest.java
- src/test/java/testing/mocks/DockerClientStub.java
Been playing around with DPS recently, and came across a bug in `docker-java` ([here](https://github.com/docker-java/docker-java/issues/2365)).
If a container is configured with `CAP_ADD` or `CAP_DROP` in lowercase, DPS fails with a nasty exception (seen below).
While waiting for `docker-java` to fix this bug, I figured it would be good if we add some defensive coding here on this side, so it won't fail all DNS lookups if there's a single bad container.
Let me know what you think!
```
17:56:16.572 [virtual-186646 ] WAR c.m.d.server.dns.RequestHandlerDefault            l=101  m=solveAndSummarizeHandlingError  status=solverFailed, currentSolverTime=12, totalTime=12, solver=SolverDocker, query=query=A:zoneminder.dj-server.lan, eClass=RuntimeException, …
```
> Fixing container inspect error
